### ISSUE TITLE
Unnecessary file in repository

### ISSUE THREAD

**Issue by jmatthiesen81** [NetInventors/sw.ext.neti_phpexcel#3]
The file "composer.lock" is unnecessary and can cause errors on other machines.

**Comment by hrombach** [comment]
removed with 33565b4098bcdafad6f5a7d559fc62c5ead1acdb

**Comment by hrombach** [comment]
after conversation with @jmatthiesen81 I reverted the removal. the lockfile should be included in VCS according to composer
